#ddev-generated
services:
  lighthouse:
    container_name: ddev-${DDEV_SITENAME}-lighthouse
    build:
      context: './lighthouseBuild'
      args:
        BASE_IMAGE: patrickhulce/lhci-client:latest
        username: $USER
        uid: $DDEV_UID
        gid: $DDEV_GID
    image: patrickhulce/lhci-client:latest-${DDEV_SITENAME}-built
    user:  '$DDEV_UID:$DDEV_GID'
    networks: [default, ddev_default]
    restart: "no"
    shm_size: ${LIGHTHOUSE_SHM_SIZE:-1gb}
    cap_add:
      - SYS_ADMIN
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    entrypoint: [ "/entrypoint.sh" ]
    environment:
      DDEV_HOSTNAME: $DDEV_HOSTNAME
      NODE_EXTRA_CA_CERTS: /mnt/ddev-global-cache/mkcert/rootCA.pem
    volumes:
    - ../reports/lighthouse:/home/$USER/reports/export
    - ../tests/lighthouse:/home/$USER/reports/config
    - .:/mnt/ddev_config:ro
    - ddev-global-cache:/mnt/ddev-global-cache
